// @ts-nocheck -- mockapi template source; stripped during generation
// This file is generated by mockapi.
// Do not edit by hand.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import YAML from 'yaml'

export type RuntimeConfig = {
  openApiRoot: string
  outputPath: string
}

const httpMethods = ['delete', 'get', 'patch', 'post', 'put'] as const

type HttpMethod = (typeof httpMethods)[number]

type OpenApiDocument = {
  paths?: Record<string, OpenApiPathItem | OpenApiRef>
}

type OpenApiRef = {
  $ref: string
}

type OpenApiPathItem = Partial<Record<HttpMethod, OpenApiOperation>> & {
  parameters?: Array<OpenApiParameter | OpenApiRef>
}

type OpenApiOperation = {
  operationId?: string
  parameters?: Array<OpenApiParameter | OpenApiRef>
  requestBody?: OpenApiRequestBody | OpenApiRef
  responses?: Record<string, OpenApiResponse | OpenApiRef>
}

type OpenApiRequestBody = {
  content?: Record<string, OpenApiMediaType>
}

type OpenApiResponse = {
  content?: Record<string, OpenApiMediaType>
}

type OpenApiMediaType = {
  schema?: OpenApiSchema | OpenApiRef
}

type OpenApiSchema = Record<string, unknown>

type OpenApiParameter = {
  in?: string
  name?: string
  required?: boolean
}

type RouteDefinition = {
  errorResponses: { status: string }[]
  method: Uppercase<HttpMethod>
  operationId: string
  parameters: Array<{
    in: string
    name: string
    required: boolean
  }>
  path: string
  requestBody: boolean
  requestBodySchema: string | null
  responseSchema: string
  statusCodes: string[]
  successStatus: number
  url: string
}

const documentCache = new Map<string, unknown>()

const isHttpUrl = (value: string) => /^https?:\/\//i.test(value)

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null

const isRef = (value: unknown): value is OpenApiRef =>
  isRecord(value) && typeof value.$ref === 'string'

const readYaml = async (source: string): Promise<unknown> => {
  const cacheKey = isHttpUrl(source) ? source : path.resolve(source)
  const cached = documentCache.get(cacheKey)

  if (cached) {
    return cached
  }

  const contents = isHttpUrl(source)
    ? await (await fetch(source)).text()
    : await readFile(path.resolve(source), 'utf8')
  const parsed = YAML.parse(contents) as unknown
  documentCache.set(cacheKey, parsed)

  return parsed
}

const resolveJsonPointer = (value: unknown, pointer: string): unknown => {
  const parts = pointer
    .replace(/^#/, '')
    .split('/')
    .filter(Boolean)
    .map((part) => part.replace(/~1/g, '/').replace(/~0/g, '~'))

  return parts.reduce<unknown>((current, part) => {
    if (!isRecord(current)) {
      throw new Error(`Cannot resolve JSON pointer ${pointer}`)
    }

    return current[part]
  }, value)
}

const resolveRef = async <T>(
  ref: OpenApiRef,
  fromSource: string,
): Promise<{ source: string; value: T }> => {
  const [sourceRef = '', pointer = ''] = ref.$ref.split('#')
  let source = fromSource

  if (sourceRef) {
    source = isHttpUrl(sourceRef)
      ? sourceRef
      : isHttpUrl(fromSource)
        ? new URL(sourceRef, fromSource).toString()
        : path.resolve(path.dirname(fromSource), sourceRef)
  }

  const document = await readYaml(source)

  return {
    source,
    value: resolveJsonPointer(document, `#${pointer}`) as T,
  }
}

const resolveValue = async <T>(
  value: T | OpenApiRef,
  fromSource: string,
): Promise<{ source: string; value: T }> =>
  isRef(value) ? resolveRef<T>(value, fromSource) : { source: fromSource, value }

const toHonoPath = (openApiPath: string) =>
  openApiPath.replace(/\{([^}]+)\}/g, ':$1')

const toPascalCase = (value: string) =>
  value
    .replace(/(^|[-_\s]+)([a-zA-Z0-9])/g, (_match, _separator, char: string) =>
      char.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, '')

const schemaExportName = (ref: string) => {
  const pointer = ref.split('#')[1] ?? ref
  const schemaName = pointer.split('/').filter(Boolean).at(-1)

  if (!schemaName) {
    throw new Error(`Cannot derive zod schema export from ${ref}`)
  }

  return `z${toPascalCase(schemaName)}`
}

const responseSchemaExportName = (operationId: string) =>
  `z${toPascalCase(operationId)}Response`

const dataTypeName = (operationId: string) => `${toPascalCase(operationId)}Data`

const responseTypeName = (operationId: string) =>
  `${toPascalCase(operationId)}Response`

const toParameter = async (
  parameter: OpenApiParameter | OpenApiRef,
  fromSource: string,
): Promise<RouteDefinition['parameters'][number]> => {
  const resolved = isRef(parameter)
    ? (await resolveRef<OpenApiParameter>(parameter, fromSource)).value
    : parameter

  if (!resolved.name || !resolved.in) {
    throw new Error(`OpenAPI parameter is missing name or in: ${JSON.stringify(resolved)}`)
  }

  return {
    in: resolved.in,
    name: resolved.name,
    required: resolved.required ?? false,
  }
}

const requestBodySchemaExport = async (
  requestBody: OpenApiRequestBody | OpenApiRef | undefined,
  fromSource: string,
) => {
  if (!requestBody) {
    return null
  }

  const resolved = await resolveValue<OpenApiRequestBody>(requestBody, fromSource)
  const schema = resolved.value.content?.['application/json']?.schema

  if (!schema) {
    throw new Error('JSON request body is missing schema.')
  }
  if (!isRef(schema)) {
    throw new Error('Mock runtime generation only supports $ref request body schemas.')
  }

  return schemaExportName(schema.$ref)
}

const successStatus = (operationId: string, responses: Record<string, unknown>) => {
  const statuses = Object.keys(responses).filter((status) => /^2\d\d$/.test(status))

  if (statuses.length !== 1) {
    throw new Error(
      `${operationId} must declare exactly one 2xx response, found ${statuses.join(', ')}`,
    )
  }

  return Number.parseInt(statuses[0] ?? '', 10)
}

const collectRoutes = async (openApiRoot: string) => {
  const root = (await readYaml(openApiRoot)) as OpenApiDocument
  const routes: RouteDefinition[] = []

  for (const [openApiPath, pathValue] of Object.entries(root.paths ?? {})) {
    const pathItemRef = isRef(pathValue)
      ? await resolveRef<OpenApiPathItem>(pathValue, openApiRoot)
      : { source: openApiRoot, value: pathValue }
    const pathItem = pathItemRef.value
    const sharedParameters = pathItem.parameters ?? []

    for (const method of httpMethods) {
      const operation = pathItem[method]

      if (!operation) {
        continue
      }
      if (!operation.operationId) {
        throw new Error(`${method.toUpperCase()} ${openApiPath} is missing operationId`)
      }

      const parameters = await Promise.all(
        [...sharedParameters, ...(operation.parameters ?? [])].map((parameter) =>
          toParameter(parameter, pathItemRef.source),
        ),
      )
      const requestSchema = await requestBodySchemaExport(
        operation.requestBody,
        pathItemRef.source,
      )
      const responseEntries = Object.entries(operation.responses ?? {})
      const errorResponses = responseEntries
        .filter(([status]) => !/^2\d\d$/.test(status))
        .map(([status]) => ({ status }))

      routes.push({
        errorResponses,
        method: method.toUpperCase() as Uppercase<HttpMethod>,
        operationId: operation.operationId,
        parameters,
        path: toHonoPath(openApiPath),
        requestBody: Boolean(operation.requestBody),
        requestBodySchema: requestSchema,
        responseSchema: responseSchemaExportName(operation.operationId),
        statusCodes: responseEntries.map(([status]) => status),
        successStatus: successStatus(operation.operationId, operation.responses ?? {}),
        url: openApiPath,
      })
    }
  }

  return routes
}

const renderUnion = (values: string[]) =>
  values.map((value) => JSON.stringify(value)).join(' | ') || 'never'

const renderRouteDefinitions = (routes: RouteDefinition[]) =>
  JSON.stringify(
    routes.map(({ errorResponses, requestBodySchema, responseSchema, successStatus, ...route }) => route),
    null,
    2,
  )

const renderTypeMap = (
  routes: RouteDefinition[],
  typeName: (operationId: string) => string,
) =>
  routes
    .map((route) => `  ${JSON.stringify(route.operationId)}: Api.${typeName(route.operationId)}`)
    .join('\n')

const renderStatusTypeMap = (routes: RouteDefinition[]) =>
  routes
    .map((route) => `  ${JSON.stringify(route.operationId)}: ${route.successStatus}`)
    .join('\n')

const renderResponseSchemas = (routes: RouteDefinition[]) =>
  routes
    .map((route) => `  ${JSON.stringify(route.operationId)}: ApiZod.${route.responseSchema},`)
    .join('\n')

const renderRequestBodySchemas = (routes: RouteDefinition[]) =>
  routes
    .filter((route) => route.requestBodySchema)
    .map((route) => `  ${JSON.stringify(route.operationId)}: ApiZod.${route.requestBodySchema},`)
    .join('\n')

const renderErrorResponseSchemas = (routes: RouteDefinition[]) =>
  routes
    .filter((route) => route.errorResponses.length > 0)
    .map((route) => {
      const schemas = route.errorResponses
        .map((response) => `    ${JSON.stringify(response.status)}: zMockErrorBody,`)
        .join('\n')

      return `  ${JSON.stringify(route.operationId)}: {
${schemas}
  },`
    })
    .join('\n')

const renderHandlers = (routes: RouteDefinition[]) =>
  routes
    .map((route) => {
      if (route.successStatus === 204) {
        return `  ${route.operationId}: async (request) => {
    await request.controllers.${route.operationId}(request.input, request.context)

    return { status: ${route.successStatus} }
  },`
      }

      return `  ${route.operationId}: async (request) => ({
    body: await request.controllers.${route.operationId}(request.input, request.context),
    status: ${route.successStatus},
  }),`
    })
    .join('\n')

const renderRuntime = (routes: RouteDefinition[]) => `// This file is generated by mockapi.
// Do not edit by hand.

import type * as z from 'zod'

import { zMockErrorBody } from '../../lib/errors.ts'
import type { MockRequestContext } from '../../lib/requestContext.ts'
import type * as Api from './contract/types.gen.ts'
import * as ApiZod from './contract/zod.gen.ts'

export {
  badRequest,
  conflict,
  MockHttpError,
  notFound,
  unexpected,
  validationError,
} from '../../lib/errors.ts'

export type GeneratedHttpMethod = 'DELETE' | 'GET' | 'PATCH' | 'POST' | 'PUT'
export type GeneratedOperationId = ${renderUnion(routes.map((route) => route.operationId))}
export type GeneratedRouteDefinition = {
  method: GeneratedHttpMethod
  operationId: GeneratedOperationId
  parameters: readonly {
    in: string
    name: string
    required: boolean
  }[]
  path: string
  requestBody: boolean
  statusCodes: readonly string[]
  url: string
}
export const generatedRouteDefinitions = ${renderRouteDefinitions(routes)} as const satisfies readonly GeneratedRouteDefinition[]
export const generatedOperationIds = generatedRouteDefinitions.map(
  (route) => route.operationId,
) as GeneratedOperationId[]
export type GeneratedOperationData = {
${renderTypeMap(routes, dataTypeName)}
}
export type GeneratedOperationResponse = {
${renderTypeMap(routes, responseTypeName)}
}
export type GeneratedOperationSuccessStatus = {
${renderStatusTypeMap(routes)}
}
type MaybePromise<T> = T | Promise<T>
export type GeneratedMockControllers = {
  [Id in GeneratedOperationId]: (
    input: GeneratedOperationData[Id],
    context: MockRequestContext,
  ) => MaybePromise<GeneratedOperationResponse[Id]>
}
export type GeneratedOperationRequest<Id extends GeneratedOperationId = GeneratedOperationId> = {
  controllers: GeneratedMockControllers
  context: MockRequestContext
  input: GeneratedOperationData[Id]
}
export type GeneratedOperationResult<Id extends GeneratedOperationId = GeneratedOperationId> = {
  [Operation in Id]: GeneratedOperationResponse[Operation] extends void
    ? { status: GeneratedOperationSuccessStatus[Operation] }
    : {
        body: GeneratedOperationResponse[Operation]
        status: GeneratedOperationSuccessStatus[Operation]
      }
}[Id]
export type GeneratedOperationHandler<Id extends GeneratedOperationId> = (
  request: GeneratedOperationRequest<Id>,
) => Promise<GeneratedOperationResult<Id>>
export const generatedRequestBodySchemas: Partial<Record<GeneratedOperationId, z.ZodType>> = {
${renderRequestBodySchemas(routes)}
}
export const generatedResponseSchemas: Record<GeneratedOperationId, z.ZodType> = {
${renderResponseSchemas(routes)}
}
export const generatedErrorResponseSchemas: Partial<Record<GeneratedOperationId, Partial<Record<string, z.ZodType>>>> = {
${renderErrorResponseSchemas(routes)}
}
export const generatedOperationHandlers = {
${renderHandlers(routes)}
} satisfies {
  [Id in GeneratedOperationId]: GeneratedOperationHandler<Id>
}
export const generatedMockRuntime = {
  generatedErrorResponseSchemas,
  generatedOperationHandlers,
  generatedRequestBodySchemas,
  generatedResponseSchemas,
  generatedRouteDefinitions,
}
`

export const generateMockRuntimeFiles = async (
  runtimeConfigs: readonly RuntimeConfig[],
) => {
  for (const config of runtimeConfigs) {
    const routes = await collectRoutes(config.openApiRoot)
    await mkdir(path.dirname(config.outputPath), { recursive: true })
    await writeFile(config.outputPath, renderRuntime(routes), 'utf8')
  }
}
