from __future__ import annotations

import unittest
from pathlib import Path
from unittest.mock import patch

from tests.support import (
    ADMIN_OPENAPI_TEMPLATE_PATH,
    PROJECT_ROOT,
    TEMPLATE_ROOT,
    MemoryFileSystem,
    profile_model,
    profile_toml,
    seed_runtime_templates,
)
from mockapi_runtime.context import create_generate_context
from mockapi_runtime.render_features import FeatureRenderService
from mockapi_runtime.render_project import ProjectRenderService
from mockapi_runtime.templates import TemplateService


class RenderServiceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.fs = MemoryFileSystem()
        seed_runtime_templates(self.fs)
        self.template_service = TemplateService(self.fs, TEMPLATE_ROOT)

    def test_project_renderer_plans_generated_and_scaffold_files(self) -> None:
        profile = profile_model(
            """\
            schemaVersion = 1

            [generator]
            name = "mockapi"
            version = "0.1.0"

            [project]
            root = "."

            [project.target]
            packagePath = "mock-server"
            packageName = "@local/mock-server"
            serverName = "Mock API"

            [[apis]]
            name = "product-api"
            openapi = "openapi.yaml"
            basePath = "/api"

            [[features]]
            name = "workspaces"

            [[operations]]
            operationId = "listWorkspaces"
            api = "product-api"
            feature = "workspaces"
            method = "GET"
            path = "/workspaces"

            [state]
            schemaVersion = 1

            [[state.slices]]
            name = "workspaces"
            recordType = "Workspace"
            array = true
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        by_path = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}
        self.assertTrue(by_path["openapi-ts.config.ts"].overwrite)
        self.assertTrue(by_path["openapi/admin.source.yaml"].overwrite)
        self.assertFalse(by_path["src/app.ts"].overwrite)
        self.assertTrue(by_path["src/generated/mock-admin/state/seed.ts"].overwrite)
        self.assertNotIn("openapi/admin.yaml", by_path)
        self.assertNotIn("src/generated/mock-admin/state/types.ts", by_path)
        self.assertIn('title: "Mock API Admin API"', by_path["openapi/admin.source.yaml"].content)
        self.assertIn("MockState:", by_path["openapi/admin.source.yaml"].content)
        self.assertIn('$ref: "../../openapi.yaml#/components/schemas/Workspace"', by_path["openapi/admin.source.yaml"].content)
        self.assertIn('x-mockapi-source-name: "product-api"', by_path["openapi/admin.source.yaml"].content)
        self.assertTrue(by_path["src/generated/mock-admin/state/seed.ts"].content.startswith("// This file is generated by mockapi."))
        self.assertIn("import type { MockState } from '../contract/index.ts'", by_path["src/generated/mock-admin/state/seed.ts"].content)
        self.assertIn("schemaVersion: 1,", by_path["src/generated/mock-admin/state/seed.ts"].content)
        self.assertIn("    workspaces: [],", by_path["src/generated/mock-admin/state/seed.ts"].content)
        self.assertNotIn('    "workspaces": [],', by_path["src/generated/mock-admin/state/seed.ts"].content)
        self.assertNotIn("mockStateSchemaVersion", by_path["src/generated/mock-admin/state/seed.ts"].content)
        self.assertIn('const basePath = "/api"', by_path["src/app.ts"].content)
        self.assertIn("basePath: basePath,", by_path["src/app.ts"].content)

    def test_project_renderer_uses_current_time_for_seed_now_default(self) -> None:
        profile = profile_model(profile_toml())
        context = create_generate_context(profile, PROJECT_ROOT)

        with patch("mockapi_runtime.render_project.current_seed_now", return_value="2026-05-26T12:34:56.789Z"):
            writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        seed = {
            write.path.relative_to(context.outRoot).as_posix(): write.content
            for write in writes
        }["src/generated/mock-admin/state/seed.ts"]
        self.assertIn('export const seedNow = "2026-05-26T12:34:56.789Z"', seed)
        self.assertIn('clock: { now: seedNow },', seed)

    def test_project_renderer_keeps_profile_seed_now_when_explicit(self) -> None:
        profile = profile_model(
            profile_toml().replace(
                "\n[state]\nschemaVersion = 1\n",
                "\n[state]\nschemaVersion = 1\n\n[state.clock]\nseedNow = \"2024-01-02T03:04:05.678Z\"\n",
            )
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        with patch("mockapi_runtime.render_project.current_seed_now") as mock_current_seed_now:
            writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        seed = {
            write.path.relative_to(context.outRoot).as_posix(): write.content
            for write in writes
        }["src/generated/mock-admin/state/seed.ts"]
        self.assertIn('export const seedNow = "2024-01-02T03:04:05.678Z"', seed)
        mock_current_seed_now.assert_not_called()

    def test_project_renderer_errors_when_admin_template_lacks_placeholder(self) -> None:
        bad_template = Path("/runtime/bad-admin.yaml")
        self.fs.write_text(bad_template, "openapi: 3.1.0\n")
        profile = profile_model(
            """\
            schemaVersion = 1

            [generator]
            name = "mockapi"
            version = "0.1.0"

            [project]
            root = "."

            [project.target]
            packagePath = "mock-server"
            packageName = "@local/mock-server"
            serverName = "Mock API"

            [state]
            schemaVersion = 1
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        with self.assertRaisesRegex(RuntimeError, "missing __MOCKAPI_ADMIN_API_TITLE__"):
            ProjectRenderService(self.fs, self.template_service, bad_template).planned_writes(context)

    def test_project_renderer_resolves_file_qualified_state_schema_refs(self) -> None:
        profile = profile_model(profile_toml().replace(
            'recordType = "Workspace"\n',
            'recordType = "Workspace"\nschemaRef = "product-api:./domains/workspaces.yaml#/components/schemas/Workspace"\n',
        ))
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        by_path = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}
        self.assertIn(
            '$ref: "../../domains/workspaces.yaml#/components/schemas/Workspace"',
            by_path["openapi/admin.source.yaml"].content,
        )
        self.assertIn('x-mockapi-source-name: "product-api"', by_path["openapi/admin.source.yaml"].content)

    def test_project_renderer_keeps_admin_builtin_state_schema_refs_local(self) -> None:
        profile = profile_model(
            profile_toml()
            + """\

            [[state.slices]]
            name = "mockClock"
            recordType = "MockClock"
            array = false
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        admin_openapi = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}[
            "openapi/admin.source.yaml"
        ].content
        self.assertIn('MockClockRecord:\n      allOf:\n        - $ref: "#/components/schemas/MockClock"', admin_openapi)
        self.assertNotIn("../../openapi.yaml#/components/schemas/MockClock", admin_openapi)

    def test_project_renderer_does_not_treat_ts_union_record_type_as_schema_ref(self) -> None:
        profile = profile_model(
            profile_toml()
            + """\

            [[state.slices]]
            name = "activeWorkspaceId"
            recordType = "Id | null"
            array = false
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        admin_source = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}[
            "openapi/admin.source.yaml"
        ].content
        self.assertIn("        - activeWorkspaceId", admin_source)
        self.assertIn("        activeWorkspaceId:\n          true", admin_source)
        self.assertNotIn("IdNullRecord:", admin_source)
        self.assertNotIn("components/schemas/Id | null", admin_source)

    def test_project_renderer_does_not_treat_ts_scalar_record_type_as_schema_ref(self) -> None:
        profile = profile_model(
            profile_toml()
            + """\

            [[state.slices]]
            name = "activeWorkspaceId"
            recordType = "string"
            array = false
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)

        admin_source = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}[
            "openapi/admin.source.yaml"
        ].content
        self.assertIn("        activeWorkspaceId:\n          type: string", admin_source)
        self.assertNotIn("StringRecord:", admin_source)
        self.assertNotIn("components/schemas/string", admin_source)

    def test_project_renderer_supports_id_counter_state_slice(self) -> None:
        profile = profile_model(
            profile_toml()
            + """\

            [[state.slices]]
            name = "idCounters"
            recordType = "Record<string, number>"
            array = false
            """
        )
        context = create_generate_context(profile, PROJECT_ROOT)

        writes = ProjectRenderService(self.fs, self.template_service, ADMIN_OPENAPI_TEMPLATE_PATH).planned_writes(context)
        by_path = {write.path.relative_to(context.outRoot).as_posix(): write for write in writes}
        admin_openapi = by_path["openapi/admin.source.yaml"].content
        seed = by_path["src/generated/mock-admin/state/seed.ts"].content

        self.assertIn("        - idCounters", admin_openapi)
        self.assertIn(
            "        idCounters:\n"
            "          type: object\n"
            "          additionalProperties:\n"
            "            type: number",
            admin_openapi,
        )
        self.assertNotIn("IdCountersRecord:", admin_openapi)
        self.assertIn('    idCounters: {} as MockState["idCounters"],', seed)

    def test_feature_renderer_skips_existing_operation_files(self) -> None:
        profile = profile_model(profile_toml())
        context = create_generate_context(profile, PROJECT_ROOT)
        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        self.fs.write_text(feature_root / "controllers/listWorkspaces.ts", "// custom\n")

        writes = FeatureRenderService(self.fs, self.template_service).planned_writes(context)

        paths = {write.path for write in writes}
        self.assertNotIn(feature_root / "controllers/listWorkspaces.ts", paths)
        self.assertNotIn(feature_root / "services/listWorkspaces.ts", paths)
        self.assertNotIn(feature_root / "repository.ts", paths)
        self.assertIn(feature_root / "seed.ts", paths)

    def test_feature_renderer_generates_only_operation_controllers(self) -> None:
        profile = profile_model(profile_toml())
        context = create_generate_context(profile, PROJECT_ROOT)
        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"

        writes = FeatureRenderService(self.fs, self.template_service).planned_writes(context)

        paths = {write.path for write in writes}
        by_path = {write.path: write for write in writes}
        self.assertIn(feature_root / "controllers/listWorkspaces.ts", paths)
        self.assertIn(feature_root / "seed.ts", paths)
        self.assertNotIn(feature_root / "services/listWorkspaces.ts", paths)
        self.assertNotIn(feature_root / "repository.ts", paths)
        self.assertIn('Pick<ProductMockControllers, "listWorkspaces">', by_path[feature_root / "controllers/listWorkspaces.ts"].content)
        self.assertIn("listWorkspaces: async", by_path[feature_root / "controllers/listWorkspaces.ts"].content)
        self.assertNotIn('"listWorkspaces": async', by_path[feature_root / "controllers/listWorkspaces.ts"].content)
        self.assertIn("  workspaces: [],", by_path[feature_root / "seed.ts"].content)
        self.assertNotIn('  "workspaces": [],', by_path[feature_root / "seed.ts"].content)

    def test_feature_renderer_skips_existing_seed_file(self) -> None:
        profile = profile_model(profile_toml())
        context = create_generate_context(profile, PROJECT_ROOT)
        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        self.fs.write_text(feature_root / "seed.ts", "// custom seed\n")

        writes = FeatureRenderService(self.fs, self.template_service).planned_writes(context)

        paths = {write.path for write in writes}
        self.assertNotIn(feature_root / "seed.ts", paths)

    def test_feature_renderer_does_not_generate_feature_modules_without_state_slices(self) -> None:
        profile = profile_model(profile_toml().replace('stateSlices = ["workspaces"]\n', ""))
        context = create_generate_context(profile, PROJECT_ROOT)
        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"

        writes = FeatureRenderService(self.fs, self.template_service).planned_writes(context)

        paths = {write.path for write in writes}
        self.assertNotIn(feature_root / "repository.ts", paths)
        self.assertNotIn(feature_root / "seed.ts", paths)


if __name__ == "__main__":
    unittest.main()
