from __future__ import annotations

import json
from dataclasses import dataclass
import textwrap
import unittest
from pathlib import Path

from tests.support import (
    PROJECT_ROOT,
    MemoryFileSystem,
    create_generator,
    default_behavior,
    profile_toml,
    seed_openapi_fixture,
    write_project,
)

from mockapi_runtime.files import planned_write
from mockapi_runtime.generate import SkillRootService, apply_template_replacements, dedupe_writes, planned_files
from mockapi_runtime.package_manager import PackageManagerCommandSet, PackageManagerResult


GENERATED_SCRIPT_HEADER = "// This file is generated by mockapi.\n// Do not edit by hand.\n\n"


def profile_with_get_workspace_operation() -> str:
    return (
        profile_toml()
        .replace('operations = ["listWorkspaces"]', 'operations = ["listWorkspaces", "getWorkspace"]')
        + textwrap.dedent(
            """\

            [[operations]]
            operationId = "getWorkspace"
            api = "product-api"
            feature = "workspaces"
            method = "GET"
            path = "/workspaces/{id}"
            """
        )
    )


def behavior_with_get_workspace_operation() -> str:
    return textwrap.dedent(
        """\
        # Mock Behavior

        ## operation:listWorkspaces
        Status: inferred

        ## operation:getWorkspace
        Status: inferred
        """
    )


@dataclass(frozen=True, slots=True)
class FakeCommandResult:
    command: str
    cwd: Path
    exitCode: int
    stdout: str = ""
    stderr: str = ""


class RecordingCommandRunner:
    def __init__(self, *, exit_codes: dict[str, int] | None = None) -> None:
        self.exit_codes = exit_codes or {}
        self.commands: list[tuple[str, Path]] = []

    def run(self, command: str, *, cwd: Path) -> FakeCommandResult:
        self.commands.append((command, cwd))
        exit_code = self.exit_codes.get(command, 0)
        return FakeCommandResult(
            command=command,
            cwd=cwd,
            exitCode=exit_code,
            stdout=f"stdout:{command}",
            stderr=f"stderr:{command}" if exit_code else "",
        )


class FakePackageManagerDetector:
    def __init__(self, *, ok: bool = True, manager: str = "npm", diagnostics: list[str] | None = None) -> None:
        self.ok = ok
        self.manager = manager
        self.diagnostics = diagnostics or []
        self.calls: list[tuple[Path, str, Path, dict[str, str]]] = []

    def detect(
        self,
        *,
        root: Path,
        profile_path: str,
        package_root: Path,
        env: dict[str, str],
    ) -> PackageManagerResult:
        self.calls.append((root, profile_path, package_root, dict(env)))
        runner = "bun run" if self.manager == "bun" else f"{self.manager} run"
        commands = (
            PackageManagerCommandSet(
                install=f"{self.manager} install",
                codegen=f"{runner} codegen",
                check=f"{runner} check",
            )
            if self.ok
            else None
        )
        return PackageManagerResult(
            ok=self.ok,
            manager=self.manager if self.ok else "",
            source="test",
            packageRoot=str(package_root),
            projectRoot=str(root),
            pathPrepend=[],
            executable=f"/fake/{self.manager}" if self.ok else None,
            executor=self.manager if self.ok else "",
            commands=commands,
            diagnostics=self.diagnostics,
        )


class GenerateTests(unittest.TestCase):
    def setUp(self) -> None:
        self.fs = MemoryFileSystem()
        self.generator = create_generator(self.fs)

    def test_smoke_generates_from_ref_based_openapi_fixture(self) -> None:
        openapi_path = seed_openapi_fixture(self.fs)
        profile_path = write_project(
            self.fs,
            openapi=None,
            profile=profile_toml().replace('openapi = "openapi.yaml"', 'openapi = "openapi/openapi.yaml"'),
            behavior=default_behavior(),
        )

        validation = self.generator.profile_validator.validate(profile_path, root=PROJECT_ROOT, cwd=PROJECT_ROOT)
        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(self.fs.is_file(openapi_path))
        self.assertIn("$ref: './domains/workspaces.yaml#/paths/workspaces'", self.fs.read_text(openapi_path))
        self.assertIn("$ref: '../shared/components.yaml#/components/schemas/Id'", self.fs.read_text(PROJECT_ROOT / "openapi/domains/workspaces.yaml"))
        self.assertTrue(validation.ok)
        self.assertTrue(result.ok)
        self.assertTrue(self.fs.is_file(PROJECT_ROOT / "mock-server/src/features/workspaces/controllers/listWorkspaces.ts"))

    def test_dry_run_returns_planned_files(self) -> None:
        write_project(self.fs)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", dry_run=True)
        self.assertTrue(result.ok)
        self.assertTrue(any(file.path.endswith("src/app.ts") for file in result.files))
        self.assertTrue(any(file.path.endswith("src/controllers.ts") for file in result.files))
        self.assertTrue(any(file.path.endswith("scripts/codegen-admin-openapi.ts") for file in result.files))
        self.assertTrue(any(file.path.endswith("openapi/admin.source.yaml") for file in result.files))
        self.assertFalse(any(file.path.endswith("openapi/admin.yaml") for file in result.files))
        self.assertTrue(any(file.path.endswith("src/features/workspaces/controllers/listWorkspaces.ts") for file in result.files))
        self.assertFalse(any(file.path.endswith("src/features/workspaces/services/listWorkspaces.ts") for file in result.files))
        self.assertFalse(any(file.path.endswith("src/features/workspaces/repository.ts") for file in result.files))
        self.assertTrue(any(file.path.endswith("src/features/workspaces/seed.ts") for file in result.files))
        self.assertTrue(all(file.action == "planned" for file in result.files))

    def test_generates_operation_controller_todo_only(self) -> None:
        write_project(self.fs)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        self.assertTrue(result.ok)
        self.assertTrue(self.fs.is_file(feature_root / "controllers/listWorkspaces.ts"))
        controller = self.fs.read_text(feature_root / "controllers/listWorkspaces.ts")
        self.assertIn(".mockapi/behavior.md anchor operation:listWorkspaces", controller)
        self.assertIn("throw new Error", controller)
        self.assertIn('Pick<ProductMockControllers, "listWorkspaces">', controller)
        self.assertIn("listWorkspaces: async", controller)
        self.assertNotIn('"listWorkspaces": async', controller)
        self.assertNotIn("../services/listWorkspaces.ts", controller)
        self.assertFalse(self.fs.exists(feature_root / "operations/listWorkspaces.ts"))
        self.assertFalse(self.fs.exists(feature_root / "services/listWorkspaces.ts"))
        self.assertFalse(self.fs.exists(feature_root / "repository.ts"))
        self.assertTrue(self.fs.exists(feature_root / "seed.ts"))
        admin_seed = self.fs.read_text(PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/seed.ts")
        self.assertIn("../../../features/workspaces/seed.ts", admin_seed)
        self.assertIn("...seedWorkspaces(context)", admin_seed)
        self.assertNotIn('"workspaces": []', admin_seed)

    def test_initial_controllers_scaffold_wires_operation_adapters(self) -> None:
        write_project(self.fs, profile=profile_with_get_workspace_operation(), behavior=behavior_with_get_workspace_operation())

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        controllers = self.fs.read_text(PROJECT_ROOT / "mock-server/src/controllers.ts")
        self.assertTrue(result.ok)
        self.assertIn("./features/workspaces/controllers/listWorkspaces.ts", controllers)
        self.assertIn("./features/workspaces/controllers/getWorkspace.ts", controllers)
        self.assertIn("...newListWorkspacesController(deps),", controllers)
        self.assertIn("...newGetWorkspaceController(deps),", controllers)
        self.assertIn("export type MockApiDependencies", controllers)
        self.assertNotIn("new WorkspacesService", controllers)
        self.assertNotIn("./features/workspaces/service.ts", controllers)
        self.assertNotIn("./features/workspaces/repository.ts", controllers)

    def test_feature_without_state_slices_gets_no_feature_modules(self) -> None:
        profile = profile_toml().replace('stateSlices = ["workspaces"]\n', "")
        write_project(self.fs, profile=profile)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        admin_seed = self.fs.read_text(PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/seed.ts")
        self.assertTrue(result.ok)
        self.assertFalse(self.fs.exists(feature_root / "repository.ts"))
        self.assertFalse(self.fs.exists(feature_root / "seed.ts"))
        self.assertNotIn("../../../features/workspaces/seed.ts", admin_seed)
        self.assertIn("workspaces: []", admin_seed)

    def test_existing_feature_repository_and_seed_are_not_rewritten(self) -> None:
        write_project(self.fs)
        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        repository_path = feature_root / "repository.ts"
        seed_path = feature_root / "seed.ts"
        self.fs.add_file(repository_path, "// custom repository\n")
        self.fs.add_file(seed_path, "// custom seed\n")

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(repository_path), "// custom repository\n")
        self.assertEqual(self.fs.read_text(seed_path), "// custom seed\n")
        self.assertFalse(any(file.path == str(repository_path) for file in result.files))
        self.assertFalse(any(file.path == str(seed_path) for file in result.files))

    def test_existing_admin_state_files_are_rewritten(self) -> None:
        write_project(self.fs)
        controller_path = PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/controller.ts"
        repository_path = PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/repository.ts"
        service_path = PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/service.ts"
        seed_path = PROJECT_ROOT / "mock-server/src/generated/mock-admin/state/seed.ts"
        self.fs.add_file(controller_path, "// custom admin controller\n")
        self.fs.add_file(repository_path, "// custom admin repository\n")
        self.fs.add_file(service_path, "// custom admin service\n")
        self.fs.add_file(seed_path, "// custom admin seed\n")

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(controller_path), f"{GENERATED_SCRIPT_HEADER}admin controller\n")
        self.assertEqual(self.fs.read_text(repository_path), f"{GENERATED_SCRIPT_HEADER}admin repository\n")
        self.assertEqual(self.fs.read_text(service_path), f"{GENERATED_SCRIPT_HEADER}admin service\n")
        self.assertTrue(self.fs.read_text(seed_path).startswith(GENERATED_SCRIPT_HEADER))
        actions_by_path = {file.path: file.action for file in result.files}
        self.assertEqual(actions_by_path[str(controller_path)], "updated")
        self.assertEqual(actions_by_path[str(repository_path)], "updated")
        self.assertEqual(actions_by_path[str(service_path)], "updated")
        self.assertEqual(actions_by_path[str(seed_path)], "updated")
        self.assertFalse(any(path.endswith("/src/generated/mock-admin/state/types.ts") for path in actions_by_path))

    def test_existing_generated_scripts_are_rewritten(self) -> None:
        write_project(self.fs)
        admin_script_path = PROJECT_ROOT / "mock-server/scripts/codegen-admin-openapi.ts"
        runtime_script_path = PROJECT_ROOT / "mock-server/scripts/lib/mockRuntimeCodegen.ts"
        self.fs.add_file(admin_script_path, "old admin script\n")
        self.fs.add_file(runtime_script_path, "old runtime script\n")

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(admin_script_path), f"{GENERATED_SCRIPT_HEADER}admin codegen\n")
        self.assertEqual(self.fs.read_text(runtime_script_path), f"{GENERATED_SCRIPT_HEADER}runtime codegen\n")
        actions_by_path = {file.path: file.action for file in result.files}
        self.assertEqual(actions_by_path[str(admin_script_path)], "updated")
        self.assertEqual(actions_by_path[str(runtime_script_path)], "updated")

    def test_legacy_feature_files_are_ignored(self) -> None:
        write_project(self.fs)

        feature_root = PROJECT_ROOT / "mock-server/src/features/workspaces"
        legacy_controller = "export const createWorkspacesController = () => ({ listWorkspaces: () => ({}) })\n"
        legacy_service = "export class WorkspacesService {}\n"
        legacy_operation = "export const createListWorkspacesController = () => ({})\n"
        self.fs.add_file(feature_root / "controller.ts", legacy_controller)
        self.fs.add_file(feature_root / "service.ts", legacy_service)
        self.fs.add_file(feature_root / "operations/listWorkspaces.ts", legacy_operation)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        controllers = self.fs.read_text(PROJECT_ROOT / "mock-server/src/controllers.ts")
        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(feature_root / "controller.ts"), legacy_controller)
        self.assertEqual(self.fs.read_text(feature_root / "service.ts"), legacy_service)
        self.assertEqual(self.fs.read_text(feature_root / "operations/listWorkspaces.ts"), legacy_operation)
        self.assertTrue(self.fs.is_file(feature_root / "controllers/listWorkspaces.ts"))
        self.assertFalse(self.fs.is_file(feature_root / "services/listWorkspaces.ts"))
        self.assertNotIn("createWorkspacesController", controllers)
        self.assertNotIn("./features/workspaces/service.ts", controllers)
        self.assertNotIn("./features/workspaces/operations/listWorkspaces.ts", controllers)

    def test_existing_operation_service_is_ignored(self) -> None:
        write_project(self.fs)
        service_path = PROJECT_ROOT / "mock-server/src/features/workspaces/services/listWorkspaces.ts"
        custom_service = "// user edit\n"
        self.fs.add_file(service_path, custom_service)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(service_path), custom_service)
        self.assertFalse(any(file.path == str(service_path) for file in result.files))

    def test_scaffold_files_are_not_rewritten(self) -> None:
        write_project(self.fs)

        first = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")
        self.assertTrue(first.ok)

        scaffold_paths = [
            PROJECT_ROOT / "mock-server/src/app.ts",
            PROJECT_ROOT / "mock-server/src/controllers.ts",
            PROJECT_ROOT / "mock-server/src/server.ts",
        ]
        for path in scaffold_paths:
            self.fs.write_text(path, f"// custom {path.name}\n")

        second = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(second.ok)
        for path in scaffold_paths:
            self.assertEqual(self.fs.read_text(path), f"// custom {path.name}\n")

    def test_renders_admin_openapi_source_from_template(self) -> None:
        profile = profile_toml().replace(
            'serverName = "Mock API"',
            'serverName = "Mock \\"Quoted\\" API"',
        )
        write_project(self.fs, profile=profile)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        admin_openapi = self.fs.read_text(PROJECT_ROOT / "mock-server/openapi/admin.source.yaml")
        self.assertTrue(result.ok)
        self.assertTrue(admin_openapi.startswith("# This file is generated by mockapi.\n# Do not edit by hand.\n\n"))
        self.assertIn('  title: "Mock \\"Quoted\\" API Admin API"\n', admin_openapi)
        self.assertIn("  /__mock/health:\n", admin_openapi)
        self.assertFalse(self.fs.exists(PROJECT_ROOT / "mock-server/openapi/admin.yaml"))

    def test_generation_fails_with_validation_diagnostics(self) -> None:
        write_project(self.fs, behavior="# Missing anchors\n")

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertFalse(result.ok)
        self.assertEqual(result.diagnostics[0]["id"], "sidecar.behavior.missingAnchor")
        self.assertEqual(result.files, [])

    def test_template_package_placeholder_is_replaced(self) -> None:
        write_project(self.fs)

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        payload = json.loads(self.fs.read_text(PROJECT_ROOT / "mock-server/package.json"))
        self.assertEqual(payload["name"], "@local/mock-server")
        self.assertEqual(
            payload["scripts"]["codegen"],
            "tsx scripts/codegen-admin-openapi.ts && openapi-ts && tsx scripts/codegen-mock-runtime.ts",
        )
        self.assertEqual(
            payload["scripts"]["codegen:contract"],
            "tsx scripts/codegen-admin-openapi.ts && openapi-ts",
        )
        self.assertEqual(payload["scripts"]["test"], "vitest run")
        self.assertEqual(payload["devDependencies"]["vitest"], "^4.1.4")
        self.assertEqual(
            self.fs.read_text(PROJECT_ROOT / "mock-server/scripts/codegen-admin-openapi.ts"),
            f"{GENERATED_SCRIPT_HEADER}admin codegen\n",
        )
        self.assertEqual(
            self.fs.read_text(PROJECT_ROOT / "mock-server/scripts/lib/mockRuntimeCodegen.ts"),
            f"{GENERATED_SCRIPT_HEADER}runtime codegen\n",
        )
        self.assertEqual(self.fs.read_text(PROJECT_ROOT / "mock-server/src/server.ts"), "server\n")
        self.assertEqual(self.fs.read_text(PROJECT_ROOT / "mock-server/.gitignore"), ".mockapi-runtime/\n")
        self.assertEqual(
            self.fs.read_text(PROJECT_ROOT / "mock-server/vitest.config.ts"),
            "export default { test: { environment: 'node', globals: true } }\n",
        )

    def test_existing_vitest_config_is_not_rewritten(self) -> None:
        write_project(self.fs)
        config_path = PROJECT_ROOT / "mock-server/vitest.config.ts"
        self.fs.add_file(config_path, "// custom vitest config\n")

        result = self.generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(config_path), "// custom vitest config\n")
        self.assertFalse(any(file.path == str(config_path) and file.action == "updated" for file in result.files))

    def test_skill_root_service_uses_env_then_errors_when_missing(self) -> None:
        fs = MemoryFileSystem()
        fs.add_file(Path("/env-skill/SKILL.md"), "# Skill\n")

        discovered = SkillRootService(fs, env={"MOCKAPI_SKILL_ROOT": "/env-skill"}, script_root=Path("/missing"), cwd=Path("/cwd")).discover()

        self.assertEqual(discovered, Path("/env-skill"))
        with self.assertRaisesRegex(RuntimeError, "Could not locate mockapi skill root"):
            SkillRootService(fs, env={}, script_root=Path("/missing"), cwd=Path("/cwd")).discover()

    def test_generate_helpers_dedupe_plan_and_replace_templates(self) -> None:
        first = planned_write(Path("/out/file.ts"), "old", overwrite=False)
        second = planned_write(Path("/out/file.ts"), "new __NAME__", overwrite=True)

        writes = apply_template_replacements(dedupe_writes([first, second]), {"__NAME__": "value"})

        self.assertEqual(writes[0].content, "new value")
        self.assertEqual(planned_files(writes)[0].path, "/out/file.ts")
        self.assertTrue(planned_files(writes)[0].overwrite)

    def test_default_generate_detects_codegen_command_without_running_codegen(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml")

        self.assertTrue(result.ok)
        self.assertEqual(runner.commands, [])
        self.assertEqual(detector.calls[0][2], PROJECT_ROOT / "mock-server")
        self.assertFalse(result.codegen.attempted)
        self.assertEqual(result.codegen.codegenCommand, "npm run codegen")
        self.assertEqual(result.packageManager["manager"], "npm")

    def test_dry_run_run_codegen_does_not_run_commands(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", dry_run=True, run_codegen=True)

        self.assertTrue(result.ok)
        self.assertTrue(result.dryRun)
        self.assertEqual(detector.calls, [])
        self.assertEqual(runner.commands, [])
        self.assertFalse(result.codegen.attempted)
        self.assertFalse(self.fs.exists(PROJECT_ROOT / "mock-server/pnpm-workspace.yaml"))

    def test_run_codegen_installs_when_node_modules_is_missing(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        package_root = PROJECT_ROOT / "mock-server"
        self.assertTrue(result.ok)
        self.assertEqual(runner.commands, [("npm install", package_root), ("npm run codegen", package_root)])
        self.assertTrue(result.codegen.attempted)
        self.assertEqual(result.codegen.installCommand, "npm install")
        self.assertEqual(result.codegen.codegenCommand, "npm run codegen")
        self.assertFalse(self.fs.exists(package_root / "pnpm-workspace.yaml"))

    def test_run_codegen_creates_pnpm_workspace_before_pnpm_install(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector(manager="pnpm")
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        package_root = PROJECT_ROOT / "mock-server"
        workspace_path = package_root / "pnpm-workspace.yaml"
        actions_by_path = {file.path: file.action for file in result.files}
        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(workspace_path), "allowBuilds:\n  esbuild: true\n")
        self.assertEqual(actions_by_path[str(workspace_path)], "created")
        self.assertEqual(runner.commands, [("pnpm install", package_root), ("pnpm run codegen", package_root)])
        self.assertEqual(result.packageManager["manager"], "pnpm")

    def test_run_codegen_keeps_existing_pnpm_workspace(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector(manager="pnpm")
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)
        package_root = PROJECT_ROOT / "mock-server"
        workspace_path = package_root / "pnpm-workspace.yaml"
        self.fs.add_file(workspace_path, "packages:\n  - .\n")

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        actions_by_path = {file.path: file.action for file in result.files}
        self.assertTrue(result.ok)
        self.assertEqual(self.fs.read_text(workspace_path), "packages:\n  - .\n")
        self.assertEqual(actions_by_path[str(workspace_path)], "skipped")
        self.assertEqual(runner.commands, [("pnpm install", package_root), ("pnpm run codegen", package_root)])

    def test_run_codegen_skips_install_when_node_modules_exists(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)
        self.fs.mkdir(PROJECT_ROOT / "mock-server/node_modules")

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        package_root = PROJECT_ROOT / "mock-server"
        self.assertTrue(result.ok)
        self.assertEqual(runner.commands, [("npm run codegen", package_root)])
        self.assertIsNone(result.codegen.installCommand)

    def test_run_codegen_failure_returns_failed_result_with_diagnostics(self) -> None:
        runner = RecordingCommandRunner(exit_codes={"npm run codegen": 2})
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)
        self.fs.mkdir(PROJECT_ROOT / "mock-server/node_modules")

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        self.assertFalse(result.ok)
        self.assertEqual(result.codegen.exitCode, 2)
        self.assertIn("Codegen failed", result.codegen.diagnostics[0])
        self.assertEqual(result.diagnostics[0]["id"], "package.codegen.failed")

    def test_run_codegen_install_failure_returns_failed_result(self) -> None:
        runner = RecordingCommandRunner(exit_codes={"npm install": 1})
        detector = FakePackageManagerDetector()
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        package_root = PROJECT_ROOT / "mock-server"
        self.assertFalse(result.ok)
        self.assertEqual(runner.commands, [("npm install", package_root)])
        self.assertEqual(result.codegen.exitCode, 1)
        self.assertIn("Dependency install failed", result.codegen.diagnostics[0])

    def test_run_codegen_detector_failure_returns_failed_result(self) -> None:
        runner = RecordingCommandRunner()
        detector = FakePackageManagerDetector(ok=False, diagnostics=["No package manager."])
        generator = create_generator(self.fs, command_runner=runner, package_manager_detector=detector)
        write_project(self.fs)

        result = generator.generate(root=PROJECT_ROOT, profile_path=".mockapi/profile.toml", run_codegen=True)

        self.assertFalse(result.ok)
        self.assertEqual(runner.commands, [])
        self.assertTrue(result.codegen.attempted)
        self.assertIn("No package manager.", result.codegen.diagnostics)
        self.assertEqual(result.diagnostics[0]["id"], "package.codegen.failed")


if __name__ == "__main__":
    unittest.main()
