// @ts-nocheck -- mockapi template source; stripped during generation
// This file is generated by mockapi.
// Do not edit by hand.

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import YAML from 'yaml'

type OpenApiRef = {
  $ref: string
  'x-mockapi-source-name'?: string
}

const dirname = path.dirname(fileURLToPath(import.meta.url))
const packageRoot = path.resolve(dirname, '..')
const adminSourcePath = path.resolve(packageRoot, 'openapi/admin.source.yaml')
const adminPath = path.resolve(packageRoot, 'openapi/admin.yaml')
const generatedHeader = '# This file is generated by mockapi.\n# Do not edit by hand.\n\n'

const documentCache = new Map<string, unknown>()
const externalRefToLocalName = new Map<string, string>()
const componentSource = new Map<string, string>()
const sourceAliases = new Map<string, string>()
const expandedLocalComponents = new Set<string>()

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const isRef = (value: unknown): value is OpenApiRef =>
  isRecord(value) && typeof value.$ref === 'string'

const isHttpUrl = (value: string) => /^https?:\/\//i.test(value)

const toPascalCase = (value: string) => {
  const result = value
    .replace(/(^|[-_\s/.]+)([a-zA-Z0-9])/g, (_match, _separator, char: string) =>
      char.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, '')

  return result || 'Schema'
}

const readYaml = async (documentPath: string): Promise<unknown> => {
  if (isHttpUrl(documentPath)) {
    throw new Error(
      `mockapi cannot inline HTTP OpenAPI schema refs into admin.yaml yet: ${documentPath}`,
    )
  }

  const resolvedPath = path.resolve(documentPath)
  const cached = documentCache.get(resolvedPath)

  if (cached) {
    return cached
  }

  const parsed = YAML.parse(await readFile(resolvedPath, 'utf8')) as unknown
  documentCache.set(resolvedPath, parsed)

  return parsed
}

const resolveJsonPointer = (value: unknown, pointer: string): unknown => {
  const parts = pointer
    .replace(/^#/, '')
    .split('/')
    .filter(Boolean)
    .map((part) => part.replace(/~1/g, '/').replace(/~0/g, '~'))

  return parts.reduce<unknown>((current, part) => {
    if (!isRecord(current)) {
      throw new Error(`Cannot resolve JSON pointer ${pointer}`)
    }
    if (!(part in current)) {
      throw new Error(`Cannot resolve JSON pointer ${pointer}: missing segment ${JSON.stringify(part)}`)
    }

    return current[part]
  }, value)
}

const resolveRefLocation = (ref: string, fromSource: string) => {
  const [sourceRef = '', pointer = ''] = ref.split('#')
  let source = fromSource

  if (sourceRef) {
    source = isHttpUrl(sourceRef)
      ? sourceRef
      : path.resolve(path.dirname(fromSource), sourceRef)
  }

  return {
    pointer: `#${pointer}`,
    source: isHttpUrl(source) ? source : path.resolve(source),
  }
}

const componentNameFromPointer = (pointer: string) => {
  const name = pointer.split('/').filter(Boolean).at(-1)

  if (!name) {
    throw new Error(`Cannot derive schema component name from ${pointer}`)
  }

  return toPascalCase(name)
}

const sourcePrefix = (source: string) => {
  const alias = sourceAliases.get(source)

  if (alias) {
    return toPascalCase(alias)
  }

  const basename = path.basename(source, path.extname(source))
  const parent = path.basename(path.dirname(source))

  return toPascalCase(`${parent}-${basename}`)
}

const allocateComponentName = (
  components: Record<string, unknown>,
  source: string,
  pointer: string,
) => {
  const baseName = componentNameFromPointer(pointer)
  const usedNames = new Set(Object.keys(components))

  if (!usedNames.has(baseName)) {
    return baseName
  }

  const prefixed = `${sourcePrefix(source)}${baseName}`

  if (!usedNames.has(prefixed)) {
    return prefixed
  }

  let index = 2
  while (usedNames.has(`${prefixed}${index}`)) {
    index += 1
  }

  return `${prefixed}${index}`
}

const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T

const ensureAdminDocument = (value: unknown) => {
  if (!isRecord(value)) {
    throw new Error('admin.source.yaml must be an OpenAPI object.')
  }

  const components = isRecord(value.components) ? value.components : {}
  value.components = components

  const schemas = isRecord(components.schemas) ? components.schemas : {}
  components.schemas = schemas

  return value as Record<string, unknown> & {
    components: {
      schemas: Record<string, unknown>
    }
  }
}

const expandValue = async (
  value: unknown,
  fromSource: string,
  adminDocument: ReturnType<typeof ensureAdminDocument>,
): Promise<void> => {
  if (Array.isArray(value)) {
    for (const item of value) {
      await expandValue(item, fromSource, adminDocument)
    }

    return
  }

  if (!isRecord(value)) {
    return
  }

  if (isRef(value)) {
    await expandRef(value, fromSource, adminDocument)
  }

  for (const child of Object.values(value)) {
    await expandValue(child, fromSource, adminDocument)
  }
}

const expandLocalComponent = async (
  componentName: string,
  adminDocument: ReturnType<typeof ensureAdminDocument>,
): Promise<void> => {
  if (expandedLocalComponents.has(componentName)) {
    return
  }

  expandedLocalComponents.add(componentName)
  const schema = adminDocument.components.schemas[componentName]

  if (!schema) {
    throw new Error(`admin.source.yaml references missing local schema ${componentName}`)
  }

  await expandValue(schema, componentSource.get(componentName) ?? adminSourcePath, adminDocument)
}

const expandRef = async (
  ref: OpenApiRef,
  fromSource: string,
  adminDocument: ReturnType<typeof ensureAdminDocument>,
): Promise<void> => {
  const originalRef = ref.$ref
  const location = resolveRefLocation(ref.$ref, fromSource)

  if (ref['x-mockapi-source-name']) {
    sourceAliases.set(location.source, ref['x-mockapi-source-name'])
    delete ref['x-mockapi-source-name']
  }

  if (location.source === adminSourcePath) {
    const componentName = componentNameFromPointer(location.pointer)
    ref.$ref = `#/components/schemas/${componentName}`
    await expandLocalComponent(componentName, adminDocument)

    return
  }

  const externalKey = `${location.source}${location.pointer}`
  const existingName = externalRefToLocalName.get(externalKey)

  if (existingName) {
    ref.$ref = `#/components/schemas/${existingName}`
    return
  }

  const localName = allocateComponentName(
    adminDocument.components.schemas,
    location.source,
    location.pointer,
  )
  externalRefToLocalName.set(externalKey, localName)
  componentSource.set(localName, location.source)
  ref.$ref = `#/components/schemas/${localName}`

  const sourceDocument = await readYaml(location.source)
  let schema: unknown
  try {
    schema = resolveJsonPointer(sourceDocument, location.pointer)
  } catch (error) {
    const detail = error instanceof Error ? ` ${error.message}` : ''
    throw new Error(
      `Cannot resolve schema ref ${originalRef} from ${fromSource}.${detail}`,
    )
  }
  if (schema === undefined) {
    throw new Error(`Cannot resolve schema ref ${originalRef} from ${fromSource}.`)
  }
  adminDocument.components.schemas[localName] = clone(schema)

  await expandLocalComponent(localName, adminDocument)
}

const adminDocument = ensureAdminDocument(await readYaml(adminSourcePath))
const mockState = adminDocument.components.schemas.MockState

if (!mockState) {
  throw new Error('admin.source.yaml is missing components.schemas.MockState.')
}

await expandLocalComponent('MockState', adminDocument)

await writeFile(adminPath, `${generatedHeader}${YAML.stringify(adminDocument)}\n`, 'utf8')
