from __future__ import annotations

import json
from pathlib import Path

from .models import ProfileApi, ProfileFeature, ProfileOperation, ProfileStateSlice
from .paths import is_http_url, relative_file_path, to_pascal_case

GENERATED_HEADER = """// This file is generated by mockapi.
// Do not edit by hand.
"""

STARTER_HEADER = """// Generated starter from .mockapi/profile.toml.
// This file is reviewable scaffold and may be edited.
"""


def quote(value: str) -> str:
    return json.dumps(value)


def api_module_name(api: ProfileApi) -> str:
    import re

    cleaned = re.sub(r"[^a-zA-Z0-9-]+", "-", api.name).strip("-")
    return cleaned or "api"


def runtime_output(api: ProfileApi) -> str:
    return api.runtimeOutput or f"src/generated/{api_module_name(api)}/mock-runtime.ts"


def contract_output(api: ProfileApi) -> str:
    return api.contractOutput or f"src/generated/{api_module_name(api)}/contract"


def openapi_input_from_package(api: ProfileApi, root: Path, out_root: Path) -> str:
    openapi = api.openapi
    if is_http_url(openapi):
        return openapi

    absolute_input = Path(openapi) if Path(openapi).is_absolute() else root / openapi
    return relative_file_path(out_root, absolute_input.resolve())


def state_type_name(state_slice: ProfileStateSlice) -> str:
    return f"{to_pascal_case(state_slice.recordType or state_slice.name)}Record"


def state_slice_property_type(state_slice: ProfileStateSlice) -> str:
    type_name = state_slice.recordType if "<" in str(state_slice.recordType or "") else state_type_name(state_slice)
    return type_name if state_slice.array is False else f"{type_name}[]"


def operation_method_name(operation: ProfileOperation) -> str:
    import re

    return re.sub(r"[^a-zA-Z0-9_$]", "_", operation.operationId)


def operation_file_name(operation: ProfileOperation) -> str:
    return f"{operation_method_name(operation)}.ts"


def operation_factory_name(operation: ProfileOperation) -> str:
    return f"new{to_pascal_case(operation_method_name(operation))}Controller"


def feature_seed_function_name(feature: ProfileFeature) -> str:
    return f"seed{to_pascal_case(feature.name)}"
