from __future__ import annotations

from datetime import datetime, timezone
import re
from pathlib import Path

from .filesystem import FileSystem
from .files import planned_write
from .models import ADMIN_OPENAPI_BUILTIN_STATE_RECORD_TYPES, GenerateContext, PlannedWrite, Profile, ProfileStateSlice
from .paths import is_http_url, relative_file_path, to_camel_case, to_pascal_case
from .schema_ref import (
    SchemaRefParts,
    is_generic_record_type,
    is_schema_component_record_type,
    parse_schema_ref,
)
from .render_utils import (
    GENERATED_HEADER,
    STARTER_HEADER,
    api_module_name,
    contract_output,
    feature_seed_function_name,
    openapi_input_from_package,
    operation_factory_name,
    operation_file_name,
    quote,
    runtime_output,
    state_type_name,
)
from .templates import TemplateService

ADMIN_OPENAPI_GENERATED_HEADER = """# This file is generated by mockapi.
# Do not edit by hand.
"""
ADMIN_OPENAPI_TEMPLATE_PATH = Path(__file__).with_name("admin_openapi.yaml")
ADMIN_OPENAPI_TITLE_PLACEHOLDER = "__MOCKAPI_ADMIN_API_TITLE__"
ADMIN_OPENAPI_MOCK_STATE_PLACEHOLDER = "__MOCKAPI_ADMIN_MOCK_STATE_SCHEMAS__"


def current_seed_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def render_openapi_ts_config(context: GenerateContext, template_service: TemplateService) -> str:
    rendered_configs = [
        f"""  {{
    input: {quote(openapi_input_from_package(api, context.root, context.outRoot))},
    output: {{
      clean: true,
      module: {{
        extension: '.ts',
      }},
      path: {quote(contract_output(api))},
      tsConfigPath: './tsconfig.json',
    }},
    plugins,
  }}"""
        for api in context.profile.apis
    ]
    rendered_configs.append(
        """  {
    input: "./openapi/admin.yaml",
    output: {
      clean: true,
      module: {
        extension: '.ts',
      },
      path: "src/generated/mock-admin/contract",
      tsConfigPath: './tsconfig.json',
    },
    plugins,
  }"""
    )

    return template_service.render(
        "openapi-ts.config.ts.tpl",
        {
            "CONFIGS": ",\n".join(rendered_configs),
            "GENERATED_HEADER": GENERATED_HEADER,
        },
    )


def render_runtime_configs(context: GenerateContext) -> str:
    rendered: list[str] = []
    for api in context.profile.apis:
        openapi_root_value = openapi_input_from_package(api, context.root, context.outRoot)
        openapi_root = (
            quote(openapi_root_value)
            if is_http_url(openapi_root_value)
            else f"path.resolve(packageRoot, {quote(openapi_root_value)})"
        )
        rendered.append(
            f"""  {{
    openApiRoot: {openapi_root},
    outputPath: path.resolve(packageRoot, {quote(runtime_output(api))}),
  }}"""
        )
    rendered.append(
        """  {
    openApiRoot: path.resolve(packageRoot, "./openapi/admin.yaml"),
    outputPath: path.resolve(packageRoot, "src/generated/mock-admin/mock-runtime.ts"),
  }"""
    )
    return ",\n".join(rendered)


def render_codegen_runtime(context: GenerateContext, template_service: TemplateService) -> str:
    return template_service.render(
        "codegen-mock-runtime.ts.tpl",
        {
            "GENERATED_HEADER": GENERATED_HEADER,
            "RUNTIME_CONFIGS": render_runtime_configs(context),
        },
    )


def yaml_key(value: str) -> str:
    return value if re.match(r"^[A-Za-z_][A-Za-z0-9_-]*$", value) else quote(value)


def indent_block(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else line for line in text.splitlines())


def schema_ref_parts(profile: Profile, state_slice: ProfileStateSlice) -> SchemaRefParts | None:
    if state_slice.schemaRef:
        return parse_schema_ref(state_slice.schemaRef)

    if state_slice.recordType in ADMIN_OPENAPI_BUILTIN_STATE_RECORD_TYPES:
        return SchemaRefParts("", f"/components/schemas/{state_slice.recordType}", admin_builtin=True)

    if len(profile.apis) == 1 and is_schema_component_record_type(state_slice.recordType):
        return SchemaRefParts(profile.apis[0].name, f"/components/schemas/{state_slice.recordType}")

    return None


def admin_openapi_ref(profile: Profile, context: GenerateContext, state_slice: ProfileStateSlice) -> str | None:
    parts = schema_ref_parts(profile, state_slice)
    if not parts:
        return None

    if parts.admin_builtin:
        return f"#{parts.fragment}"

    api = next(api for api in profile.apis if api.name == parts.api_name)
    if is_http_url(api.openapi):
        return f"{api.openapi}#{parts.fragment}"

    api_input = Path(api.openapi) if Path(api.openapi).is_absolute() else context.root / api.openapi
    schema_input = (
        Path(parts.source_path)
        if parts.source_path and Path(parts.source_path).is_absolute()
        else api_input.parent / parts.source_path
        if parts.source_path
        else api_input
    )
    return f"{relative_file_path(context.outRoot / 'openapi', schema_input.resolve())}#{parts.fragment}"


def scalar_schema_for_ts_type(ts_type: str) -> str:
    normalized = ts_type.strip()
    if normalized == "string":
        return "type: string"
    if normalized == "number":
        return "type: number"
    if normalized == "boolean":
        return "type: boolean"
    if normalized in {"unknown", "any"}:
        return "true"
    return "true"


def generic_record_schema(state_slice: ProfileStateSlice) -> str:
    record_type = str(state_slice.recordType or "")
    match = re.match(r"^Record<string,\s*([^>]+)>$", record_type)
    additional_properties = scalar_schema_for_ts_type(match.group(1)) if match else "true"
    if additional_properties == "true":
        return "type: object\nadditionalProperties: true"
    return f"type: object\nadditionalProperties:\n{indent_block(additional_properties, 2)}"


def state_slice_property_schema(state_slice: ProfileStateSlice) -> str:
    if is_generic_record_type(state_slice.recordType):
        item_schema = generic_record_schema(state_slice)
    elif is_schema_component_record_type(state_slice.recordType) or state_slice.schemaRef:
        item_schema = f"$ref: {quote(f'#/components/schemas/{state_type_name(state_slice)}')}"
    else:
        item_schema = scalar_schema_for_ts_type(str(state_slice.recordType or "unknown"))

    if state_slice.array is False:
        return item_schema

    return f"type: array\nitems:\n{indent_block(item_schema, 2)}"


def state_slice_extension_properties(state_slice: ProfileStateSlice) -> list[tuple[str, str]]:
    properties: list[tuple[str, str]] = []
    if state_slice.idField:
        properties.append((state_slice.idField, "type: string"))
    if state_slice.softDeleteField:
        properties.append((state_slice.softDeleteField, "type: string\nformat: date-time\nnullable: true"))
    return properties


def render_extension_schema(state_slice: ProfileStateSlice) -> str:
    properties = state_slice_extension_properties(state_slice)
    if not properties:
        return "type: object"

    rendered_properties = []
    for name, schema in properties:
        rendered_properties.append(f"{yaml_key(name)}:\n{indent_block(schema, 2)}")

    rendered_property_block = "\n".join(rendered_properties)
    return f"type: object\nproperties:\n{indent_block(rendered_property_block, 2)}"


def render_state_record_schema(profile: Profile, context: GenerateContext, state_slice: ProfileStateSlice) -> str:
    external_ref = admin_openapi_ref(profile, context, state_slice)
    if external_ref is None:
        return generic_record_schema(state_slice)

    schema_parts = schema_ref_parts(profile, state_slice)
    source_name_line = f"\n    x-mockapi-source-name: {quote(schema_parts.api_name)}" if schema_parts and schema_parts.api_name else ""
    extensions = state_slice_extension_properties(state_slice)
    if not extensions:
        return f"allOf:\n  - $ref: {quote(external_ref)}{source_name_line}"

    extension_schema = render_extension_schema(state_slice).replace("\n", "\n    ")
    return f"allOf:\n  - $ref: {quote(external_ref)}{source_name_line}\n  - {extension_schema}"


def render_mock_state_schemas(profile: Profile, context: GenerateContext) -> str:
    required = ["schemaVersion", "clock", *(state_slice.name for state_slice in profile.state.slices)]
    required_block = "\n".join(f"        - {yaml_key(name)}" for name in required)
    properties = [
        f"""        schemaVersion:
          type: integer
          enum:
            - {profile.state.schemaVersion}""",
        """        clock:
          $ref: '#/components/schemas/MockClock'""",
        *[
            f"        {yaml_key(state_slice.name)}:\n{indent_block(state_slice_property_schema(state_slice), 10)}"
            for state_slice in profile.state.slices
        ],
    ]
    record_schemas = [
        f"    {state_type_name(state_slice)}:\n{indent_block(render_state_record_schema(profile, context, state_slice), 6)}"
        for state_slice in profile.state.slices
        if schema_ref_parts(profile, state_slice) is not None
    ]

    return "\n".join(
        [
            "    MockState:",
            "      type: object",
            "      additionalProperties: false",
            "      required:",
            required_block,
            "      properties:",
            "\n".join(properties),
            *record_schemas,
        ]
    )


def render_admin_openapi(context: GenerateContext, fs: FileSystem, admin_openapi_template_path: Path = ADMIN_OPENAPI_TEMPLATE_PATH) -> str:
    profile = context.profile
    server_name = profile.project.target.serverName
    template = fs.read_text(admin_openapi_template_path)
    if ADMIN_OPENAPI_TITLE_PLACEHOLDER not in template:
        raise RuntimeError(f"{admin_openapi_template_path} is missing {ADMIN_OPENAPI_TITLE_PLACEHOLDER}.")
    if ADMIN_OPENAPI_MOCK_STATE_PLACEHOLDER not in template:
        raise RuntimeError(f"{admin_openapi_template_path} is missing {ADMIN_OPENAPI_MOCK_STATE_PLACEHOLDER}.")

    body = template.replace(
        ADMIN_OPENAPI_TITLE_PLACEHOLDER,
        quote(f"{server_name} Admin API"),
    ).replace(
        ADMIN_OPENAPI_MOCK_STATE_PLACEHOLDER,
        render_mock_state_schemas(profile, context),
    )
    return f"{ADMIN_OPENAPI_GENERATED_HEADER}\n{body.rstrip()}\n"


def render_app(profile: Profile, template_service: TemplateService) -> str:
    uses_base_path_option = len(profile.apis) == 1
    runtime_imports = "\n".join(
        [
            "import { generatedMockRuntime as adminRuntime } from './generated/mock-admin/mock-runtime.ts'",
            *[
                f"import {{ generatedMockRuntime as {to_camel_case(api.name)}Runtime }} from './generated/{api_module_name(api)}/mock-runtime.ts'"
                for api in profile.apis
            ],
        ]
    )
    registrations = "\n".join(
        [
            """  registerGeneratedMockRoutes(app, {
    controllers,
    runtime: adminRuntime,
  })""",
            *[
                f"""  registerGeneratedMockRoutes(app, {{
    basePath: {"basePath" if uses_base_path_option else quote(api.basePath or "")},
    controllers,
    runtime: {to_camel_case(api.name)}Runtime,
  }})"""
                for api in profile.apis
            ],
        ]
    )

    return template_service.render(
        "app.ts.tpl",
        {
            "DEFAULT_BASE_PATH": quote(profile.apis[0].basePath or "") if uses_base_path_option else quote(""),
            "ROUTE_REGISTRATIONS": registrations,
            "RUNTIME_IMPORTS": runtime_imports,
            "STARTER_HEADER": STARTER_HEADER,
        },
    )


def render_controllers(context: GenerateContext, template_service: TemplateService) -> str:
    profile = context.profile
    operations = profile.operations
    product_imports = "\n".join(
        f"""import {{
  generatedRouteDefinitions as {to_camel_case(api.name)}GeneratedRouteDefinitions,
  type GeneratedMockControllers as {to_pascal_case(api.name)}GeneratedMockControllers,
}} from './generated/{api_module_name(api)}/mock-runtime.ts'"""
        for api in profile.apis
    )
    operation_imports = "\n".join(
        f"import {{ {operation_factory_name(operation)} }} from './features/{operation.feature}/controllers/{operation_file_name(operation)}'"
        for operation in operations
    )
    controller_spreads = "\n".join(
        f"    ...{operation_factory_name(operation)}(deps),"
        for operation in operations
    )
    product_types = (
        " & ".join(f"{to_pascal_case(api.name)}GeneratedMockControllers" for api in profile.apis)
        or "Record<string, never>"
    )
    operation_count = (
        " + ".join(f"{to_camel_case(api.name)}GeneratedRouteDefinitions.length" for api in profile.apis)
        or "0"
    )

    return template_service.render(
        "controllers.ts.tpl",
        {
            "CONTROLLER_SPREADS": controller_spreads,
            "OPERATION_COUNT": operation_count,
            "OPERATION_IMPORTS": operation_imports,
            "PRODUCT_IMPORTS": product_imports,
            "PRODUCT_TYPES": product_types,
            "STARTER_HEADER": STARTER_HEADER,
        },
    )


def seed_value_for_slice(state_slice: ProfileStateSlice) -> str:
    if state_slice.array is False:
        return f"{{}} as MockState[{quote(state_slice.name)}]"
    return "[]"


def feature_owned_state_slices(profile: Profile) -> dict[str, tuple[ProfileStateSlice, ...]]:
    state_slices_by_name = {state_slice.name: state_slice for state_slice in profile.state.slices}
    return {
        feature.name: tuple(state_slices_by_name[name] for name in feature.stateSlices if name in state_slices_by_name)
        for feature in profile.features
    }


def render_state_seed(profile: Profile, template_service: TemplateService) -> str:
    seed_now = profile.state.clock.seedNow if profile.state.clock and profile.state.clock.seedNow else current_seed_now()
    owned_by_feature = feature_owned_state_slices(profile)
    owned_slice_names = {
        state_slice.name
        for state_slices in owned_by_feature.values()
        for state_slice in state_slices
    }
    seed_imports = [
        f"import {{ {feature_seed_function_name(feature)} }} from '../../../features/{feature.name}/seed.ts'"
        for feature in profile.features
        if owned_by_feature.get(feature.name)
    ]
    fallback_slice_seeds = [
        f"    {state_slice.name}: {seed_value_for_slice(state_slice)},"
        for state_slice in profile.state.slices
        if state_slice.name not in owned_slice_names
    ]
    feature_seed_spreads = [
        f"    ...{feature_seed_function_name(feature)}(context),"
        for feature in profile.features
        if owned_by_feature.get(feature.name)
    ]
    seed_import_block = "\n".join(seed_imports)

    return template_service.render(
        "state-seed.ts.tpl",
        {
            "FALLBACK_SLICE_SEEDS": "\n".join(fallback_slice_seeds),
            "FEATURE_SEED_SPREADS": "\n".join(feature_seed_spreads),
            "GENERATED_HEADER": GENERATED_HEADER,
            "SEED_NOW": quote(seed_now),
            "SEED_IMPORTS": f"{seed_import_block}\n" if seed_imports else "",
            "SCHEMA_VERSION": str(profile.state.schemaVersion),
        },
    )


class ProjectRenderService:
    def __init__(
        self,
        fs: FileSystem,
        template_service: TemplateService,
        admin_openapi_template_path: Path = ADMIN_OPENAPI_TEMPLATE_PATH,
    ) -> None:
        self.fs = fs
        self.template_service = template_service
        self.admin_openapi_template_path = admin_openapi_template_path

    def planned_writes(self, context: GenerateContext) -> list[PlannedWrite]:
        out_root = context.outRoot
        profile = context.profile
        return [
            planned_write(
                out_root / "openapi-ts.config.ts",
                render_openapi_ts_config(context, self.template_service),
                overwrite=True,
            ),
            planned_write(
                out_root / "scripts/codegen-mock-runtime.ts",
                render_codegen_runtime(context, self.template_service),
                overwrite=True,
            ),
            planned_write(
                out_root / "openapi/admin.source.yaml",
                render_admin_openapi(context, self.fs, self.admin_openapi_template_path),
                overwrite=True,
            ),
            planned_write(out_root / "src/app.ts", render_app(profile, self.template_service), overwrite=False),
            planned_write(out_root / "src/controllers.ts", render_controllers(context, self.template_service), overwrite=False),
            planned_write(out_root / "src/generated/mock-admin/state/seed.ts", render_state_seed(profile, self.template_service), overwrite=True),
        ]
